language: node_js
cache: yarn
jobs:
  include:
  - stage: test
    script: yarn lint
  - stage: npm-bundle
    script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
    deploy:
      edge: true
      provider: npm
      email: bameyrick@gmail.com
      api_key:
        secure: DolXK/REQ/Ju0agzaf76lBsplWPHA1BJkrKlPa+CH3hAoKcMdVNlLI1voVI+IGftWpZnzX6WIwXpBdVxPkXM9rg2sMyLdgNpAOZPgswsZ+KsAF5cmMzsTRMFkl1LwzNAAivKvnm7eRKePD6vdPZU6bzlixx+Ew751MNU5qZDJ9vUAZu0G69BFKFj3bCKCKWZ0kmBUrUoBcLOb5XLZBN8t2bvI6gcS+8x3G5Wdwwj5A0Lmd+SXrXbLqnqu901jRiQWYUaFv0knWJgfUIHWJxTVwd0Cgi7GAh+s3rUEDTU0UoUPXgMUHXoPikUURazZFgTPOMJK1nMp1wa0Rz9VZ4NPtDE1bBgp0Vt5rQrRDRJPRTtf27emC1+T47d9E9t94q+xV9QmaFEZHSHUAxh+UK/r17mUG9NKfb/Rd/rKHw8YNTAlTpP/WyKlpWHWxNVvXrn7fNRW0HTGF/WgQuRRPsC4jTjHsJHs3KkaRL0XV5kp4Vit29vLyKarCQA/Vlc21GUdquZuKIHZUIxD4k+8RhClMMHQla4KzpScUAJ/HRzJpaEpCWDymoaMWSsvMuA8yNktKQRyQcaXXyWzW4/56a1p0zNm5UMdZzcTTs96btSKRgI55iSNNY7souEhmlHB3XYUiYPu7xMTsgDw8TbR6mCQi5HnLQOYPlz4+CHaiimIn4=
      on:
        tags: true
        repo: bameyrick/prevent-overscrolling
stages:
- name: test
  if: tag IS NOT present
- name: npm-bundle
  if: tag IS present
