language: node_js
node_js:
- 14.16.1
cache: yarn
jobs:
  include:
  - stage: test
    script: yarn lint
  - stage: npm-bundle
    script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
    deploy:
      edge: true
      provider: npm
      email: bameyrick@gmail.com
      api_key:
        secure: aSvl573ZtkygWBhoeG7yDfb8+S5D2awsKGTfUUTbdt1ZIE5qYXCtA40XKj9HIOobUhiYSrRmdQR/1fkS9c6nd5J870vmnexWv2krsXTQENcuWO+m2dd+X2dLSdu+eB41pCvCLx0LLd+z6gZ7LDpGu+7+I0kvsRqa/kAc/i08M35OuQJGxm+Y35XWUzdvpwOZm4Dr8aZf80243HoTMeYIHl1a0f+0J9ivQycwbJtCRPrL2pVm/25fvmo9BHNi4BSd/kuMP5RMpwPC+nr1Jjn7NMkHAEK8pmgF7hLodY4Z7LLlkMHPLARKj62HWEXcTy5jLjczTQVv/w4Cu1AE7kw1yOc4MIpTIOA+twKs1+bS1h1UD7KiQ6E4YgxlBAvRbn6blBGwfGDO39YrRvJxeOxQj/90WtZ/w3K2w6X03fZLA29V+WKUCf7B6U7wAfgu9lmpUlz2hcUZwnmjCbiImtMpTZtxQi90vv0B8z0re+p2/pxqnwuISKVSUt9RT++Uj9ymfaMb9hfZIb3xdP/evBry5GMMkLqUt/d2ZnwrFhbQ6hKoPPkyNO17C3frXFDDFJt5TqB2MDqimBmN5UEIysB/o91/kGD9RQQPT5jSyjgudDrDp39d5/pXJLMe86SlEvP1kLIdLhlXJ8OMguqj1uW6KNay8Bk6ZrALdtdJx5HQs4o=
      on:
        tags: true
        repo: bameyrick/prevent-overscrolling
stages:
- name: test
  if: tag IS NOT present
- name: npm-bundle
  if: tag IS present
